[package]
name = "bft_interp"
version = "0.1.0"
authors = ["Thomas Preston <thomas.preston@codethink.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bft_types = { path = "../bft_types" }
thiserror = "1.0"
